# Generated by Django 5.0.4 on 2024-06-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_migrate_unique_brands'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='Shoe',
        ),
    ]
