# Generated by Django 5.0.4 on 2024-06-27 12:44

from django.db import migrations


class Migration(migrations.Migration):
    def create_unique_brands(apps, schema_editor):
        shoe = apps.get_model('main_app', 'Shoe')
        unique_brands = apps.get_model('main_app', 'UniqueBrands')

    dependencies = [
        ('main_app', '0003_rename_show_shoe'),
    ]

    operations = [
    ]
