# Generated by Django 5.0.4 on 2024-06-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lecture',
            new_name='lecturer',
        ),
    ]
