# Generated by Django 5.0.4 on 2024-06-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_lecture_course_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
