# Generated by Django 5.0.4 on 2024-06-28 14:09

from django.db import migrations


def set_age_group_by_year(apps, schema_editor):
    persons = apps.get_model('main_app', 'Person')

    objects = persons.objects.all()

    for obj in objects:
        if obj.age <= 12:
            obj.age_group = 'Child'
        elif obj.age <= 17:
            obj.age_group = 'Teen'
        else:
            obj.age_group = 'Adult'

    persons.objects.bulk_update(objects, ['age_group'])


def reverse_set_age_group_by_year(apps, schema_editor):
    persons = apps.get_model('main_app', 'Person')
    for person in persons.objects.all():
        person.age_group = person._meta.get_field('age_group').default
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group_by_year, reverse_set_age_group_by_year)
    ]
