# Generated by Django 5.0.6 on 2024-06-30 12:44

from django.db import migrations

def set_rarity_by_price(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items_objects = item_model.objects.all()

    for item in items_objects:
        if item.price <= 10:
            item.rarity = 'Rare'
        elif item.price <= 20:
            item.rarity = 'Very Rare'
        elif item.price <= 30:
            item.rarity = 'Extremely Rare'
        else:
            item.rarity = 'Mega Rare'

    item_model.objects.bulk_update(items_objects, ['rarity'])


def reverse_set_rarity_by_price(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    for item in item_model.objects.all():
        item.rarity = item._meta.get_field('rarity').default
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity_by_price, reverse_set_rarity_by_price)
    ]
