# Generated by Django 5.0.6 on 2024-06-30 14:05

from django.db import migrations


def new_price_by_brand(apps, schema_editor):
    MULTIPLY = 120

    brands = apps.get_model('main_app', 'Smartphone')

    smartphones = brands.objectall()
    for smartphone in smartphones:
        smartphone.price = len(smartphone.brand) * MULTIPLY
        smartphone.save()


def set_category_by_brand(apps, schema_editor):
    brands = apps.get_model('main_app', 'Smartphone')

    smartphone_objects = brands.objects.all()

    for category in smartphone_objects:
        price = category.price
        category.category = 'Cheap' if price < 750 else 'Expensive'
        category.save()


def reverse_price_and_category(apps, schema_editor):
    smartphones = apps.get_model('main_app', 'Smartphone')

    smartphone_objects = smartphones.objects.all()

    for smartphone in smartphone_objects:
        smartphone.category = 'No category'
        smartphone.price /= 120 * len(smartphone.category)
        smartphone.save()


def set_price_and_category(apps, schema_editor):
    new_price_by_brand(apps, schema_editor)
    set_category_by_brand(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reverse_price_and_category)
    ]
