# Generated by Django 5.0.6 on 2024-07-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_modify_delivery_and_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
