# Generated by Django 5.0.4 on 2024-07-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_restaurantreview_regularrestaurantreview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcriticrestaurantreview',
            old_name='food_clinic_cuisine_area',
            new_name='food_critic_cuisine_area',
        ),
    ]
