# Generated by Django 5.0.4 on 2024-07-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_food_clinic_cuisine_area_foodcriticrestaurantreview_food_critic_cuisine_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularrestaurantreview',
            options={'ordering': ['-rating'], 'verbose_name': 'Restaurant Review', 'verbose_name_plural': 'Restaurant Reviews'},
        ),
    ]
