# Generated by Django 5.0.4 on 2024-07-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_regularrestaurantreview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularrestaurantreview',
            options={'ordering': ('-rating',), 'verbose_name': 'Restaurant Review', 'verbose_name_plural': 'Restaurant Reviews'},
        ),
    ]
