# Generated by Django 5.0.4 on 2024-08-01 13:06

import main_app.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[main_app.custom_validators.ValueInRangeValidator(0, 10, message=None)]),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='release_year',
            field=models.PositiveIntegerField(validators=[main_app.custom_validators.ValueInRangeValidator(1990, 2023, message=None)]),
        ),
    ]
